version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql-database
    restart: always
    command: --bind-address=0.0.0.0
    environment:
      MYSQL_DATABASE_HOST: db
      MYSQL_DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasktag
      MYSQL_USER: cleverit
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql